.github/workflows/gitops.yml
いつぞやの配信を拝見dockerイメージのビルドにキャッシュを使うようにしてみました。
* 現状2分台でCIが終了している事
* 手元で簡易的な動確はしましたが、環境依存含めてほんとうにこれで大丈夫かは確認が必要な事
が懸念としてあります。
Contributeの規約が無かった為勢いでプルリク送らさせて頂きましたが、問題あれば遠慮無く閉じて下さって大丈夫です!
=> Use cache for docker image build

.github/workflows/gitops-stg.yml
- main merge 時に staging, tagged 時に production が release されるよう GitHub Actions を修正
- 以下の PR を先に merge
- cloudnativedaysjp/dreamkast-infra#11
=> separate prd & stg in gitops Action

src/components/Chat/Chat.tsx
webSocket経由でチャットメッセージを受け取ってsetMessagesする際にnewChatMessageMapするように変更。
なお、初回レンダリング時にAPIから取得する際も同じ方法を使っている
=> チャットが更新されなくなることがある問題の対応

package.json, src/components/Chat/Chat.tsx, src/components/Chat/internal/ChatMessageForm/ChatMessageForm.tsx, src/components/Chat/internal/ChatMessageForm/styled.ts, yarn.lock
ref #73
* 終了した動画のChat欄は閉鎖する
* 登壇者が質問にあとから答えたいパターンも考慮して返信は可能のまま
=> 発表終了した動画ではChatに新規書き込みできないようにする

.github/workflows/gc.yaml, .github/workflows/gitops-dev.yml, .github/workflows/release.yml
- `release/{major,minor,patch}` label を付けて PR を merge すると、自動で現在の latest tag から {major,minor,patch} をインクリした tag を push する GitHub Action を追加
- `release/{major,minor,patch}` label を付けた際に gitops-dev , gc GitHub Action が動作しないようにした
- https://github.com/cloudnativedaysjp/dreamkast/pull/569
=> 自動で新バージョンの tag を付与する GitHub Actions を追加

.github/workflows/gc.yaml, .github/workflows/gitops-dev.yml, .github/workflows/gitops-prd.yml, .github/workflows/gitops-stg.yml
* 従来: dreamkast-infra に対して push to main
* これ以降 : push to temporary branch && create PR && merge PR
これにより、複数 GitHub Actions が同時に走ることによる push Error を回避する
* merge 前に https://github.com/cloudnativedaysjp/dreamkast-infra にて[ブランチの自動削除機能](https://docs.github.com/ja/github/administering-a-repository/managing-the-automatic-deletion-of-branches) を有効化してもらいたいです
* これがないと、 2 回目以降の push 時に GitHub Actions が dreamkast-infra に対して同名 branch を push しようとしてエラーする
https://github.com/cloudnativedaysjp/dreamkast/pull/513 と同様の PR
=> dreamkast-infra の資材更新方法変更

src/components/Sponsors/Sponsors.tsx
Fix #95
Fadeにするとスポンサーロゴがクリックできない問題が発覚。
とりあえずFade消したらクリックできるようになった。
横スクロールにあった不安定なスクロール挙動は今のところ見受けられないのでこれで
=> Fadeやめて縦スクロールにした

.github/workflows/eslint.yml, .github/workflows/gc.yaml, .github/workflows/gitops-dev.yml, .github/workflows/jest.yml, .github/workflows/release.yml
調べた限り GitHub API だと PullRequest 作成と label 付与を同時に出来無さそうだったので、 PR title で From bot であるかどうかを判別するようにしました
参考: https://github.com/cloudnativedaysjp/dreamkast-ui/pull/105
=> release用PRであることを判別する要素を label から title に変更

.github/workflows/gitops-stg.yml, .github/workflows/release.yml
* fix typo
* git tag を push するのに https://github.com/showks-containerdaysjp のトークンを利用するようにした
* Action の push 契機では Actions が走らないという仕様に対応
* 参考: https://www.yslibrary.net/2020/04/18/actions-checkout-v2-push/
=> modify GitHub Actions

src/components/Chat/internal/ChatBox/internal/ChatMessage/ChatMessage.tsx
- MM: 月
- mm: 分
fix https://github.com/cloudnativedaysjp/dreamkast-ui/issues/121
=> チャットメッセージの時刻表示が間違っていた

src/components/BoothPage/BoothPage.tsx, src/components/BoothPage/styled.ts
fix https://github.com/cloudnativedaysjp/dreamkast-ui/issues/123
dangerouslySetInnerHTMLをつかっているが、APIが返してくるテキストはadmin画面内で設定したもので制御可能なので問題ないだろうと思う
長期的にはAPIにはhtmlを返させないようにしたいが。
https://ja.reactjs.org/docs/dom-elements.html
=> ブース説明などのaタグや改行を反映させる

schemas/swagger.yml, src/client-axios/api.ts, src/components/TalkSelector/TalkSelector.tsx, src/components/Track/Track.tsx, src/pages/index.tsx
- TalkSelectorにDay1/Day2両方のセッションが表示されていた問題の修正
- ConferenceDays情報をAPIから取得し、その日のセッションだけをGETするように変更
- TalkSelectorに表示されているセッション一覧が開始時刻順になっていない問題を修正
- TalkSelector上にCM用のセッションが表示されてしまっている問題を修正
- show_on_timetable=trueのセッションのみ表示する
fix https://github.com/cloudnativedaysjp/dreamkast-ui/issues/119
fix https://github.com/cloudnativedaysjp/dreamkast-ui/issues/120
=> TalkSelectorについて3点修正

src/components/Layout/__tests__/__snapshots__/Layout.spec.tsx.snap, src/components/Menu/DesktopMenu.tsx, src/components/Menu/MobileMenu.tsx, src/components/Track/Track.tsx
Fix #163 
CI/CD ConferenceではBoothいらないのでリンクを削除
CNDT2021で復活する可能性はなくはないのでコンポーネントは消さずにいる
=> Remove booth link

src/components/Track/Track.tsx
https://github.com/cloudnativedaysjp/dreamkast-ui/pull/155 で視聴者のシステム時刻に応じてTalk一覧を取得する機能がコメントアウトされていたのでrevertする
=> revert tmp code for cicd2021

src/pages/discussionboard.tsx
=> Discussion Boardのリンク変更(CI/CDからCNDT)

.github/workflows/cron-labeling.yml
updated_at が 3 日以上前の PR に対して `reviewapps/ignore` label を付与する GitHub Actions を作成
=> add cron-labeling action

src/pages/index.tsx
デフォルトのトラックIDがハードコードされているとそのトラックを使わないイベントでUIを表示したときにトラックが選択されていない状態になる
=> sessionStorageにview_track_idがないはtracks apiから取得してきたTrackの配列先頭を使う

src/components/Track/Track.tsx, src/components/TrackSelector/TrackSelector.tsx
Fix https://github.com/cloudnativedaysjp/dreamkast/issues/1198
今まではKarteのタイミングでアンケートを表示していたので、セッション視聴途中にアンケートが出ることがある苦情があった。
なのでWebSocketでセッション切り替えを受け取ったタイミングで、切り替え前のセッションに関するアンケートをトリガーするようにした
=> Improve survey timing

src/components/Track/Track.tsx
=> Fix countdonw

.github/release.yml, .github/renovate.json5, .github/workflows/build.yml, .github/workflows/eslint.yml, .github/workflows/gitops-prd.yml, .github/workflows/gitops-stg.yml, .github/workflows/jest.yml, .github/workflows/push-tag-by-releasebot.yml, .github/workflows/release.yml, renovate.json
* renovate
* npm (minor, patch バージョンのみ), github-action, docker系(minor, patch バージョンのみ) でそれぞれグループ化した (グループ化した単位で PR が作成される)
* video.js は cloudnativedaysjp/dreamkast#1494 にて CI がコケているため npm のグループから除外
* renovate 産の PR には`dependencies` ラベルを付与
* .github/release.yml
* GitHub Release のテンプレートを記述
* 具体例: https://github.com/cloudnativedaysjp/seaman/releases/tag/v0.0.4
* Actions
* 0d728fd
* rename: release.yml > push-tag-by-releasebot.yml
* create release.yml : タグが付与されたら GitHub Release を作成する
* update gitops-*.yml: dreamkast-infra リポジトリに出した PR を squash merge するようにした
* eebbe48
* seaman によるリリース用 PR にて以下の action が走らないようにした
* build.yml
* eslint.yml
* jest.yml
* gitops-*.yml において不要行を削除
=> Update some configs for CI 

.prettierignore
perttierがgeneratedなコードや.next配下も対象としていて、時間がかかっていた & 不必要なコード修正になっていたので、ignoreするようにしました
=> Add .prettierignore to prevent lint check of generated codes

src/components/Chat/Chat.tsx
ChatBoxのevent propsに値が設定されておらず、結果としてchat削除時のガード節を突破できず削除ができない状態になっていたので、eventを追加しました。
```TypeScript
const onMenuClick = (e: React.MouseEvent<HTMLElement>) => {
const selectedMessageId = e.currentTarget.getAttribute('data-messageId')
if (!selectedMessageId || !event) return  // <- ここでこけてしまいます
const api = new ChatMessageApi(
new Configuration({ basePath: window.location.origin }),
)
const newChatMessage = {
eventAbbr: event.abbr,
body: 'このメッセージは削除されました',
}
api.apiV1ChatMessagesMessageIdPut(selectedMessageId, newChatMessage)
setAnchorEl(null)
}
```
特にconsole.errorをはいたりthrowしたりしないので、サイレントな不具合になっていたように見えます。
一通り動作確認して動いていそうではありますが、コードを全て追いかけることはできていないので、まずいケースがあればご指摘いただけると助かります（eventが設定されている方が正しい状態に見えるので、大丈夫だとは思うのですが）
=> fix: Add missing props of ChatBox to enable Chat deletion

src/components/Chat/Chat.tsx, src/components/Chat/internal/ChatBox/ChatBox.tsx, src/components/Chat/internal/ChatBox/ChatMessageMenu/ChatMessageMenu.tsx, src/components/Chat/internal/ChatBox/internal/ChatMessage/ChatMessage.tsx, src/components/Chat/internal/ChatMessageForm/ChatMessageForm.tsx, src/components/Chat/internal/ChatMessageRequest/index.ts, src/components/TalkInfo/TalkInfo.tsx, src/components/TalkInfo/__tests__/TalkInfo.spec.tsx, src/components/TalkSelector/TalkSelector.tsx, src/components/Track/Track.tsx, src/util/chat.ts
openapi clientを使っている箇所を全てRTK Queryに置き換えました。
https://github.com/cloudnativedaysjp/dreamkast-ui/pull/298 で整備した基盤を使うことで、いくつかの技術負債も一緒に返済しています。
- basePath: window.location.origin がAPI callの都度使われている
- cnsec2022がハードコードされている
- 自前で作り込んでいるpollingをRTK Queryのpollingに移行
cookieも引き続き飛ぶので、現backendに対しての後方互換性を担保しています。
（dkの方で後方互換についてコメントしましたが、よく考えたら同一ドメインの間は変わらずcookieが飛ぶので、dk-uiが先に進む分には後方互換担保が可能でした > @jacopen ）
依存している https://github.com/cloudnativedaysjp/dreamkast-ui/pull/298 が in review なので、一旦そこに向けてPRを切っています。
=> Replace to RTK Query

src/store/baseApi.ts, src/store/reauth.ts
dk-uiで401になったときにdkに飛ばして再度認証を要求する処理が局所的に入っている状態だったので、RTK Queryのapi clientで一元的に処理するようにしました。
リダイレクト処理は、ここから引っ張って来ています。
https://github.com/cloudnativedaysjp/dreamkast-ui/pull/305/files#r996382108
ドメイン分離するとこの処理だと動かなくなりますが、分割後も対応できるように作り込むとYAGNIになってしまうので、一旦このままとさせてください。
=> 401 error handling on RTK BaseQuery

src/components/TalkInfo/styled.ts
セッション概要に改行などが含まれている場合、それを表示に反映したいのでCSSを設定します
=> enable pre-wrap to display abstract

src/components/Chat/Chat.tsx, src/components/Chat/internal/ChatBox/ChatBox.tsx, src/components/Chat/internal/ChatBox/ChatMessageMenu/ChatMessageMenu.tsx, src/components/Chat/internal/ChatBox/internal/ChatMessage/ChatMessage.tsx, src/components/Chat/styled.ts, src/components/IvsPlayer/IvsPlayer.tsx, src/components/IvsPlayer/__tests__/__snapshots__/IvsPlayer.spec.tsx.snap, src/components/Layout/__tests__/__snapshots__/Layout.spec.tsx.snap, src/components/Layout/styled.ts, src/components/Player/__tests__/__snapshots__/Player.spec.tsx.snap, src/components/TalkInfo/TalkInfo.tsx, src/components/TalkInfo/styled.ts, src/components/TalkSelector/TalkSelector.tsx, src/components/TalkSelector/__tests__/__snapshots__/TalkSelector.spec.tsx.snap, src/components/TalkSelector/styled.ts, src/components/Track/Track.tsx, src/components/TrackSelector/__tests__/__snapshots__/TrackSelector.spec.tsx.snap, src/components/TrackSelector/styled.ts, src/components/common/VideoToggleButton.tsx, src/pages/[eventAbbr]/ui/index.tsx, src/pages/index.tsx, src/store/index.ts, src/store/settings.ts, src/styles/styled.ts
オフライン参加時にvideoを見せないようにしました。
- settings redux storeを追加
- profileをsettings redux storeに配置して、各componentはredux storeから読み出すように変更（propsのバケツリレーをやめるrefactoringを含む）
- showVideo stateをreduxに追加し、trueのときのみIvsPlayerを描画
- showVideo stateをtoggleするボタンを追加
- 上記ボタンは、オフライン参加のときのみ表示
- オンライン時はdefaultでvideoが表示され、ボタンが出てこない。オフライン時はdefaultはvideoが表示されず、ボタンが表示されるので、押した場合のみvideo表示に切り替え
- 独自で設定しているmarginがあると切替時にformatが崩れてしまうので、独自marginを極力除去しつつMUIのGridに任せるように修正
- 結果として要らなくなったouter containerを、simplifyするために除去（refactoring）
- video非表示モード時に高さが短すぎてfooterが真ん中らへんに表示されてしまったので、コンテンツが途中で終わってもfooterは下部に表示されるように修正
video非表示の場合、以下のような画面になります
=> Layout for in-person attendees

src/components/Track/Track.tsx
on air talkがない場合でも、talk選択をしない限り初期状態はon goingのIVS videoIdを使うようにしました。
=> fix: Force set on-going IVS videoId when no onair talk

src/components/Menu/DesktopMenu.tsx
とりあえずtarget blankでシンプルにリンクしちゃう
モバイルからはMiroは見ないかなと思ってそっちにはリンク入れてないです
=> Add miro link

src/components/Chat/Chat.tsx, src/components/TrailMap/TrailMap.tsx, src/components/hooks/useStampCompleteBonus.ts, src/pages/[eventAbbr]/ui/get-session-point.tsx, src/util/trailMap.ts
各セッションタイムスロットにつき1回限定で、ポイントを付与する実装を追加しました。
backend側で重複排除を入れているので何回投げても大丈夫なのですが、何度も投げられるのもあれなので、session storageに投げた実績を記録して、2回目以降は投げないようにしています。
（backendで重複排除しているので、仮にsession storageをクリアして投げられたとしても、ポイントが付与されることはないです）
=> Give bonus point when sent chat on each session

src/components/Layout/Layout.tsx, src/components/Layout/styled.ts, src/components/Menu/DesktopMenu.tsx, src/components/Menu/MobileMenu.tsx
- 参加ガイドへのリンクを追加
- ロゴのリンクをSPAとして動くように変更
- モバイルで見たときにメニューをDrawerにする
=> add link to Guide

schemas/swagger.yml, src/components/TrailMap/TrailMap.tsx, src/components/TrailMap/TrailMapPointHistory.tsx, src/components/TrailMap/styled.ts, src/generated/dreamkast-api.generated.ts
ポイントヒストリー機能を追加しました。
こんな感じで、何のポイントが付与されているのか確認できます。
これリリースするとむしろ問い合わせが増える気がしなくもないので、リリースするかしないかは要議論です。。。
=> feat: Point history on trail map modal

src/components/Chat/internal/ChatMessageForm/ChatMessageForm.tsx, src/components/Chat/internal/ChatMessageForm/styled.ts, src/components/Chat/internal/ChatMessageRequest/index.ts
fix https://github.com/cloudnativedaysjp/dreamkast/issues/1689
チャットで送れる文字数のバリデーションをUIでも行います。Dk本体で512文字を上限としているのでUIも揃えておきます。
- 入力した文字数が512文字以上になったらWarningメッセージを表示する
- 入力した文字数が512文字以上になったら送信ボタンを無効にする
以下、上限を越えたときのスクリーンショット（最大文字数は一時的に変更しているので512ではない）
=> validate chat message length

.github/workflows/build.yml
dk-uiのdocker tagが、commit hashとbranch名だけ付与される形になっていて、latestやsemver tagが付与されていませんでした。
dkの方のdocker-composeではdk-uiの `main` が参照されていましたが、このmainは2021年にビルドされたimageを指していて、docker-composeで起動するdk-uiは機能しない状態でした。
今後複数人で開発していくうえでよろしくないので、docker-compose側はlatestにし、こっちはmain mergeされたらlatest tagがつくように修正します。
docker tagの追加だけなのでセルフマージして、期待値通りにtagがつくか動作確認させてください。
=> chore: update build GitHubAction to add docker tag of latest and semver

src/components/Chat/Chat.tsx, src/components/Track/Track.tsx, src/store/auth.ts
local devでのbackend accessをcross originにしたのですが、dk-ui側もwebsocketだけはドメイン分離対応前と同じwindow.location.hostを参照していて、環境変数で与えられたbackendを見に行っていなかったので、修正しました。
dreamkast側のallowed-originも直しています: https://github.com/cloudnativedaysjp/dreamkast/pull/1828
=> Fix: Correct action cable endpoint

src/components/Menu/hooks.ts, src/components/Track/Track.tsx, src/components/TrackSelector/LiveTrackList.tsx, src/components/TrackSelector/TrackSelector.tsx, src/components/TrackSelector/__tests__/TrackSelector.spec.tsx, src/components/TrackSelector/hooks.ts, src/components/TrackSelector/styled.ts, src/components/hooks/useGetTalksAndTracks.ts, src/pages/[eventAbbr]/ui/index.tsx, src/pages/index.tsx, src/store/settings.ts
セッションを切り替えなくても、ライブセッションが見れるviewを追加しました。
以下の２つを追加しています。
- track selectorにマウスオーバーすると、tooltipが表示されてトラック情報が見れる
- track selectorの横のボタンをクリックすると、トラック一覧のモーダルが表示される。モーダル上でトラックを選択すると、モーダルが消えて対象のトラックに切り替わる
それぞれの画面キャプチャは以下のとおりです
=> Live session view

src/components/Chat/Chat.tsx, src/components/Track/Track.tsx
url pathを直接連結するバカをやらかした結果、productionの環境変数で与えられる値だと正しく動かなかったため、ちゃんとURL classを使う方式に直しました。
=> fix: Correct action-cable url path

package.json, src/components/Chat/Chat.tsx, src/components/Track/Track.tsx, src/store/auth.ts
prodのwebsocket cors対応がまだなのでプレイベント時にrevertしたやつ、このままだとlocal devができないので戻させてください。
リハーサルまでに、api gatewayとbackendの対応もやります。
あと、 `yarn dev` だけで開発しているとpackageが最新化されない問題の対処として、 `yarn install --frozen-lockfile` をするようにしました
=> Fix: undo revert correct action cable endpoint

Dockerfile
docker buildでyarnするときにキャッシュをきかせる
=> use yarn cache on docker build

src/config.ts, src/pages/_app.tsx, src/store/auth.ts
websocketもapi gateway経由でやりたかったのですが、いろいろ作り込みが発生しそうで複雑化しそうだったので、直接dkにアクセスするようにしました。
この対応をmergeしたら、staging/prod環境のマニフェストにも環境変数の追加が必要です
=> fix: add NEXT_PUBLIC_DK_URL env var to access dk directly only when using websocket

src/components/Layout/ErrorLayout.tsx, src/components/Layout/styled.ts, src/context/auth.tsx, src/pages/404.tsx, src/pages/_app.tsx, src/pages/_error.js, src/pages/_error.tsx
プレイベントで発生した、環境変数バインドなしでauth0のendpointを叩きにいってしまう問題、およびエラーが出たときに適切なエラー画面が出ない問題に対処しました。
具体的には、以下を実施しています。
- Sentryのために追加したerror handlerに、error pageを追加
- 存在しないエンドポイントを叩いて404になった際にもSentryにreportが上がってしまうのを避けるために、404用のエラーページを追加
- 環境変数が失われてしまっている場合は、auth0のendpointを叩きに行く前にfail fastさせる
一部リファクタリングが入っています。
- _app.tsxが責務持ち過ぎだったので、auth関連を分離
- _error.jsをtsx化
エラー画面は以下な感じです。
文言の修正は、コメントいただければ対応します。
デザインがいけてねえ！という場合は、デザインセンスがないのでコミット積んでいただけると助かります:bow:
=> Fix improve error handling

src/components/TrackSelector/PTrackSelectorButtonGroup.tsx
上部のトラック選択について、HtmlTooltipでwrapしたことでButtonGroupが自動でselected扱いにしてくれなくなりデグレっていたので、明示的にselectedにするように修正しました
=> fix: Show selected effect on TrackSelector button group

src/components/Track/Track.tsx, src/components/TrackSelector/hooks.ts, src/components/hooks/__tests__/useRunAfter.spec.tsx, src/components/hooks/useRunAfter.ts, src/pages/[eventAbbr]/ui/index.tsx, src/store/__tests__/settings.spec.tsx, src/store/settings.ts
現状、Live talk更新のaction cableイベントが発火されたときに、全クライアントが一斉にtalk/trackのfetchを行う実装となっており、負荷増が懸念されることから、talk/trackの最新化のAPI callを減らすとともに、タイミングをばらつかせることで負荷を平準化しました。
live talkの更新はaction cableから渡されるデータだけを用いて行います。
talk/trackの最新化は、複数trackのうちはじめにlive talkの切り替わりが発生してから5分程度（厳密には270s〜330sの中のランダムな値）経過した後に1回だけ行うようにしました。
=> Reduce api call on live talk update

src/components/hooks/usePostSessionPointEvent.ts
live talkが始まってない状態でセッション視聴によるスタンプ取得のQRコードを読み込むと、デッドロックになってしまう事象がでました。この状態になると、ローディングのグルグル画面が表示されたままdk-uiにアクセスできなくなります。
ユーザがこの事象にハマることは原則ありえないですが、スタッフはこのケースにハマることがありえてしまい、かつこうなるとsession storageのデータを消すしか対処がなくなるので、デッドロックにならないように修正しました。
やったことは、onAir talkがない分岐のところで、ただfail fastさせるだけではなく、loading画面のrenderingの解消とsession storageの破棄をする、という処理を追加しただけです。
=> fix: Prevent blocking dashboard-page rendering when session-point QR code loaded but there are no live talk

src/components/TrailMap/hooks.ts, src/components/TrailMap/internal/StampCard.tsx
オンラインユーザが条件を満たしてTrailMapモーダルを開いてスタンプを獲得した際に、pointEventを永続化している最中に画面の動きがなくて止まっているみたいに見えるので、skeletonを表示するようにしました。
=> fix: show loading skeleton during stamp saving

src/components/IvsPlayer/IvsPlayer.tsx, src/components/IvsPlayer/__tests__/__snapshots__/IvsPlayer.spec.tsx.snap, src/store/__tests__/settings.spec.tsx, src/store/settings.ts, src/testhelper/fixture.ts
not onAir && not videoIdなtalkに対してアーカイブ画面を表示したら、以下の問題がでたので、対処しました。
- オープニングや休憩なども「アーカイブ完了まで〜〜」という表示が出てしまう
- まだ開始していないtalkでも「アーカイブ完了まで〜〜」という表示が出てしまう
それぞれ、まだ未開始のtalkを選択できてしまった場合は「開始までお待ち下さい」、完了した休憩スロットには「セッションは終了しました」とだけ表示するようにしました。
=> fix: not to show now-archiving when intersection slot and talks not started yet

src/components/hooks/useGetTalksAndTracks.ts
事前登録セッションを表示したあと、メイン画面に戻ると、通常のfetchの前にrefetchが実行されてしまう結果エラーになり、真っ白な画面が表示される事象が出ていたので、その対処です。
=> fix: Not to call refetch when initial query not completed

src/components/TalkSelector/TalkSelector.tsx
TalkSelectorの時刻更新において、functionをreturnするのではなく即時実行されており、結果としてcomponent destroy時ではなくすぐにsetIntervalがstopされて、時間の更新がされなくなっていました。その修正です。
=> fix: Real-time update available talks on TalkSelector

.env.development, codegen.ts, package.json, src/__generated__/fragment-masking.ts, src/__generated__/gql.ts, src/__generated__/graphql.ts, src/__generated__/index.ts, src/components/Layout/Layout.tsx, src/components/Menu/DesktopMenu.tsx, src/components/Menu/MobileMenu.tsx, src/components/TalkInfo/TalkInfo.tsx, src/components/Track/Track.tsx, src/components/hooks/__tests__/useViewerCount.spec.tsx, src/components/hooks/useViewerCount.ts, src/config.ts, src/pages/[eventAbbr]/ui/get-point/[pointEventId]/index.tsx, src/pages/[eventAbbr]/ui/get-session-point/[sessionPointEventId]/index.tsx, src/pages/[eventAbbr]/ui/index.tsx, src/pages/_app.tsx, src/testhelper/store.tsx, yarn.lock
CNDF2023向けに、以下を実施しました。
- TrailMap関連の実装をコメントアウト（backendの変更により現実装は流用できないこともあり、feature flagを導入することがYAGNIだと思ったので、TODOコメントを書きつつコメントアウトに留めました）
- GraphQLを使えるように、Apolloを導入しました。
- viewer-countのAPI callをdk-weaverに対応しました。
- graphql-datagenも導入し、書いたGraphQL queryに応じてresponse typeが自動生成されるようにしました。
- GraphQL test用のhelperを書きました。test自体は、msw（mock service worker）がnativeにGraphQL対応していたので、それを使うだけでシュッと書けました。
環境変数が追加されています。staging/prodへのrelease前に、 `NEXT_PUBLIC_WEAVER_URL` を各環境のmanifestに追加する必要があります。
=> Update for CNDF2023

src/components/Menu/DesktopMenu.tsx, src/components/Menu/MobileMenu.tsx, src/components/Menu/hooks.ts, src/pages/[eventAbbr]/ui/index.tsx, src/pages/[eventAbbr]/ui/info/index.tsx, src/pages/_app.tsx
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/452 に対処しました。
`/ui/info からtimetableに行って、戻ると /info にredirectされてしまう` の件は抜本対処はしていませんが、とりあえず別タブで開くことで発生を抑止できるので、それで対処とさせてください。
=> fix: Address issue-452

schemas/swagger.yml, src/components/Layout/Layout.tsx, src/components/Layout/styled.ts, src/components/TalkSelector/TalkSelector.tsx, src/components/TalkSelector/__tests__/TalkSelector.spec.tsx, src/components/TalkSelector/__tests__/__snapshots__/TalkSelector.spec.tsx.snap, src/components/Track/Track.tsx, src/generated/dreamkast-api.generated.ts, src/store/settings.ts
リハーサル機能を追加しました。
https://github.com/cloudnativedaysjp/dreamkast/pull/2029/files
で追加されたフラグを有効にすると、以下のように挙動が変わります。
- internal=falseのconferenceDay recordを取得し、そのうち1つめの日のtalksを取得します（カンファレンス1日目のレコードになるはずです）
- なお、明示的にリハを行っている日のinternal=trueのconferenceDayがある場合は、そちらを優先します。同日のconferenceDayを作っていない場合に、上記の挙動になります。
- 現在時刻によらず、任意のtalkを選択できます（対象のtalkが未来時刻であってもdisableされません）
- リハーサルモードであることがわかるように、以下のようにヘッダの色が変わります。
=> feat: Rehearsal view

package.json, src/context/auth.tsx, src/pages/[eventAbbr]/ui/index.tsx, src/store/auth.ts, yarn.lock
リハーサル中でも開催前でも、いつでもdk-uiにアクセスできるようになっていますが、opened以外のときはアクセスできないようにしました。
ただし運営はアクセスできるようにしたいので、auth0で何かしらのroleに与えられている人は除外するようにしています（運営に所属している人は、少なくとも1つのroleには属しているであろうと仮定。次のconferenceのadminかを見るとより厳密ですが、がちがちに固めたいわけではないのでこれで十分と判断しました）
気になるのは以下2点です。
- カンファレンス終了後、closedになってもしばらくdk-uiにアクセスできた方が良い？（アーカイブ配信やコメントを見るためにアクセスする人がいる？）
- 運営（特にbroadcastチーム）だけど、auth0で何もroleをアサインされていない人もいる？（その場合は、別の方法で運営を判断する必要があります）
=> feat: Restrict access when not opened

src/components/Sponsors/Sponsors.tsx, src/components/Sponsors/styled.ts
ロゴがはみ出さないようにしました。
後半になるにつれて若干上に上がっていく事象は解決できていませんが、はみ出しはなくなっています。
（react-slick、挙動がよくわからない。。。）
=> fix: Place sponsor logo inside the slick slider container

src/components/TalkInfo/TalkInfoLT.tsx, src/components/TalkInfo/index.tsx, src/components/TrackLT/TrackLT.tsx, src/components/TrackLT/index.tsx, src/components/TrackSelector/HtmlTooltip.tsx, src/components/TrackSelector/LiveTalkModalButton.tsx, src/components/TrackSelector/PTrackSelectorButtonGroup.tsx, src/components/TrackSelector/ShowLTButton.tsx, src/components/TrackSelector/TrackSelector.tsx, src/components/TrackSelector/__tests__/LiveTalkModalButton.spec.tsx, src/components/TrackSelector/__tests__/__snapshots__/PLiveTrackList.spec.tsx.snap, src/components/TrackSelector/__tests__/__snapshots__/PTrackSelectorButtonGroup.spec.tsx.snap, src/components/TrackSelector/styled.ts, src/pages/[eventAbbr]/ui/index.tsx, src/store/settings.ts
https://www.notion.so/pfem/Community-LT-UI-6b863feebe314bf4b9e6d78e11881ba4
で頂いた要件に従い、コミュニティLTを表示する画面を実装しました。
以下のような感じで表示されます。
=> feat: Community LT page

.github/workflows/build-tag.yml
tag buildの方にSENTRY_AUTH_TOKENがついていませんでした。
=> fix: Add SENTRY_AUTH_TOKEN env var to tag build

src/pages/[eventAbbr]/ui/admin/check_in_event/index.tsx, src/pages/[eventAbbr]/ui/admin/check_in_session/index.tsx, src/pages/[eventAbbr]/ui/index.tsx, src/pages/[eventAbbr]/ui/info/index.tsx, src/pages/_app.tsx
safariで3rd party tracking cookie blockingが有効なブラウザで、infoやcheck_in_event にアクセスすると /authroizeが都度走ってしまい /ui にredirectされる件の対処です。
そもそも、上記の事象は、
1. 各pageにアクセスしたときに、access_tokenの取得処理（/authorizeのcall）が走ってしまう
2. 3rd party cookieがblockされると、auth0 libraryのgetTokenSilentlyが通らない
3. redirectを伴う再認証処理が走ってしまう
が原因です。
一方で、初回アクセス時に認証してaccess_tokenは取得済であり、そもそも1で /authorize のcallが走ることがよくないです。
これは、各pageごとにwithAuthProviderを実行しており、pageの切替時にAuthProviderがdestroy-and-recreateされてしまっているからです。
NextjsのPageRouterを使っている場合、_app.tsxで定義されているtop levelのRootAppであれば、pageを切り替えても引き継がれます。AuthProviderの実行をここに移すことで、pageを切り替えてもstateが維持され、/authorizeのcallが実行されないようにしました。
この対応により、safariでも/info が表示できることを確認しました。
1点、今回の対応により無認証のページが表示できなくなっています。
ただ、これに関しては別の方式で対応すべきであり、pageを切り替えても認証状態は維持される方が望ましいので、今回の対応は無認証ページが混在する場合でも導入するべきと考えます。
=> fix: Move AuthProvider to the RootApp to share between all page components

src/components/Menu/internal/AdminMobileMenu/AdminMobileMenu.tsx
NextLinkにして、page全体のre-renderingが発生しないようにしました。
=> fix: Use nextlink for check_in_operation pages

src/store/settings.ts
プレイベをdkでやらなかった場合に、カンファレンス前日にプレイベの予定が入っていることが多いですが、このケースにおいてdkから取得できた日付を優先すると、前日リハでプレイベ側のデータを取りに行ってしまい困ります。
リハーサルモードの場合は、プレイベの日だろうがカンファレンス当日のデータを取りに行くようにしました。
=> fix: Force rehearsal mode even when the pre-conference or conference day

next.config.js, sentry.client.config.js, sentry.edge.config.js, sentry.properties, sentry.server.config.js
- Sentryをクラウド版に移行するため、DSNをクラウド版のSentryのものに修正しました
=> Update Sentry DSN

src/components/hooks/useViewerCount.ts
- ライブセッション、アーカイブセッションのどちらでも、今見ているトラックとセッション情報が送られるように修正する
=> オンエアが切り替わった際に閲覧中のセッション情報も切り替える
