- .github/workflows/gc.yaml
> Add GC workflow

- .github/workflows/gitops.yml
cache有効化したにしては遅いと思ったら肝心のBuildkitを有効化しておりませんでした…
申し訳ないです…これで有効化されてキャッシュも正しく機能する筈…です…
> Buildkitの有効化をし忘れてたので修正

- .github/workflows/gitops.yml
- README.md
- docker-compose.yaml
- nginx/lb.conf
ローカル環境でLB(nginx)、Dreamkastセット(Rails, MySQL, Redis)を建てられるようにしました。
> Add docker-compose for local development

- package.json
- eslintでfixされるのでprettierは不要
- erslintの設定を明示する
- git addはなくてもＯＫ
> lint-staged修正

- src/components/Track/Track.tsx
- src/pages/index.tsx
https://github.com/cloudnativedaysjp/dreamkast/pull/526 を先にマージする必要があります
> websocket経由でオンエアの切り替え情報を受け取ったら配信するトークを切り替える

- src/components/Chat/Chat.tsx
- src/components/Chat/internal/ChatBox/internal/ChatMessage/styled.ts
- src/components/Chat/internal/ChatMessageForm/ChatMessageForm.tsx
- src/components/Chat/internal/ChatMessageForm/styled.ts
- src/components/TalkSelector/TalkSelector.tsx
- src/components/Track/Track.tsx
- src/components/TrackSelector/TrackSelector.tsx
- src/components/TrackSelector/__tests__/TrackSelector.spec.tsx
- src/pages/index.tsx
* Chatでメッセージの行数に合わせてカードの大きさを変えるようにする
* 空白のメッセージを飛ばせないようにする
*  talksのonAirフラグをみて、trueならtracks側の"videoId"をPlayerに入れる
> Live画面と動画データをonAirステータスに応じて切り替え

- schemas/swagger.yml
- src/client-axios/api.ts
- src/client-axios/common.ts
- src/components/Track/Track.tsx
先にDreamkast側でconference_idsを実装されないと実装テストはできない
> conference_day_idsを設定

- src/components/Track/Track.tsx
- Messageを受け取った際にPlayerも切り替わるように
- 別トラックの更新には影響されないようにした
> message受け取った際にPlayerが切り替わっていなかった

- src/components/Chat/Chat.tsx
fix https://github.com/cloudnativedaysjp/dreamkast-ui/issues/65
> talk切り替え時に再接続する処理がうまく動いていなかった

- src/components/Layout/Layout.tsx
- src/components/Layout/__tests__/__snapshots__/Layout.spec.tsx.snap
- src/components/Layout/styled.ts
fix https://github.com/cloudnativedaysjp/dreamkast-ui/issues/68
fix https://github.com/cloudnativedaysjp/dreamkast-ui/issues/64
> リンクは新規タブで開くようにする

- src/components/Sponsors/Sponsors.tsx
> スポンサーロゴの表示を改善した

- src/components/Track/Track.tsx
> conferenceDayIdsを本番の6,7に変更

- src/components/Chat/Chat.tsx
- src/components/Chat/internal/ChatBox/ChatBox.tsx
- src/components/Chat/internal/ChatMessageForm/ChatMessageForm.tsx
- src/components/Chat/internal/ChatMessageForm/styled.ts
- src/components/Chat/internal/ChatReplyForm/ChatReplyForm.tsx
- src/components/Chat/internal/ReactionButton/ReactionButton.tsx
* コメントやリアクションを投稿したあとは3秒間ボタンをdisabledにする
* 新規メッセージを最下部に表示する
* 基本的に常に最新のメッセージを表示するようにスクロール位置を固定
* オートスクロールはCheckboxで制御
* メッセージの改行を禁止 
* Enterでコメントを送信可能にする
* 質問かどうかは送信ボタンで区別しているのでEnterで送れるのは通常のメッセージのみ
ref #90
ref #91
ref #92
ref #93
> Chatをいろいろ変更

- src/components/BoothPage/BoothPage.tsx
- src/components/BoothPage/styled.ts
- src/components/Booths/Booths.tsx
- src/components/Booths/styled.ts
- src/components/Layout/Layout.tsx
- src/components/Layout/__tests__/__snapshots__/Layout.spec.tsx.snap
- src/components/Menu/DesktopMenu.tsx
- src/components/Menu/MobileMenu.tsx
- src/components/Miro/Miro.tsx
- src/components/Miro/index.tsx
- src/components/Miro/styled.ts
- src/pages/discussionboard.tsx
- src/styles/styled.ts
> Add discussion board

- src/components/TalkInfo/TalkInfo.tsx
- src/components/TalkInfo/__tests__/__snapshots__/TalkInfo.spec.tsx.snap
fix https://github.com/cloudnativedaysjp/dreamkast-ui/issues/122
> CNDTではなくCNDO

- src/components/Booths/Booths.tsx
- src/components/Chat/Chat.tsx
- src/components/Track/Track.tsx
- src/pages/index.tsx
fix https://github.com/cloudnativedaysjp/dreamkast-ui/issues/117
> remove debug log

- src/components/Chat/Chat.tsx
> isVisibleFormの初期値をtrueに

- src/pages/discussionboard.tsx
> Replace miro id

- src/components/IvsPlayer/IvsPlayer.tsx
- src/components/IvsPlayer/__tests__/__snapshots__/IvsPlayer.spec.tsx.snap
> 再生時にミュートしない

- src/components/IvsPlayer/IvsPlayer.tsx
- src/components/IvsPlayer/__tests__/IvsPlayer.spec.tsx
- src/components/Track/Track.tsx
Reverts cloudnativedaysjp/dreamkast-ui#182
> Revert "アーカイブ動画の場合はシークバーを表示する"

- src/components/Layout/__tests__/__snapshots__/Layout.spec.tsx.snap
- src/components/Menu/DesktopMenu.tsx
- src/components/Menu/MobileMenu.tsx
- src/pages/jobboard.tsx
> add Job board

- src/components/TalkSelector/TalkSelector.tsx
https://github.com/cloudnativedaysjp/dreamkast-ui/pull/155 の一部をrevert
> 開始時刻まで選択できないように戻す

- schemas/swagger.yml
- src/client-axios/api.ts
- src/components/Chat/Chat.tsx
- src/components/Menu/DesktopMenu.tsx
- src/util/chat.ts
https://github.com/cloudnativedaysjp/dreamkast/pull/1012 で `GET /api/v1/chat_message` のテストを追加しようとしていて、その過程でスキーマを更新した。スキーマ更新に伴う対応をUIでも行う。
> /api/v1/chat_messagesのスキーマ変更に伴う更新

- package.json
- yarn.lock
https://github.com/cloudnativedaysjp/dreamkast-ui/issues/149 に伴う事前バージョンアップ作業です
> Upgrade nextjs to 10.0.8 to introduce sentry

- .github/workflows/actionlint.yml
- .github/workflows/build.yml
- .github/workflows/eslint.yml
- .github/workflows/gitops-prd.yml
- .github/workflows/gitops-stg.yml
- .github/workflows/jest.yml
- .github/workflows/release.yml
- Dockerfile
> improve ci

- .github/workflows/build.yml
ref. https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1652785580611269
> remove trigger conditions because reviewapp-operator unsupport it

- src/components/IvsPlayer/IvsPlayer.tsx
- src/components/IvsPlayer/__tests__/IvsPlayer.spec.tsx
- src/components/IvsPlayer/__tests__/__snapshots__/IvsPlayer.spec.tsx.snap
- src/components/IvsPlayer/styled.ts
- src/components/TalkSelector/TalkSelector.tsx
- src/components/Track/Track.tsx
> セッション自動切り替え時のカウントダウン実装

- src/components/TalkInfo/TalkInfo.tsx
viewer_countの名前変更でこけてたので修正しました
> fix:/Rename viewer_count

- schemas/swagger.yml
- src/generated/dreamkast-api.generated.ts
dreamkast側でCIが走りきらないうちにたて続けにmergeして、dreamkast-infra側にcommitのapi doc imageの最新revisionがpushされてしまったせいで、後段のswagger.ymlの変更点のPRが作られなくなってしまいました。
CIの処理を分割すればよいのですが、ちょっと手間なので、手動でPRを作成しました。
swagger.yamlの移動とrtk-query-codegenを叩いただけなので、そのままmergeさせていただきます。
> Manual PR (dreamkast swagger.yml update)

- src/components/Chat/Chat.tsx
- src/components/Layout/__tests__/Layout.spec.tsx
- src/components/Menu/DesktopMenu.tsx
- src/components/Menu/MobileMenu.tsx
- src/components/Track/Track.tsx
- src/components/TrailMap/StampCard.tsx
- src/components/TrailMap/TrailMapModal.tsx
- src/components/TrailMap/styled.ts
- src/pages/[eventAbbr]/ui/index.tsx
- src/store/authSelector.ts
- src/store/settings.ts
- src/util/stampCollecting.ts
ポイント・スタンプラリー機能について、まだ途中ですが、一旦切りがいいところまで進んだのでPRをあげさせてください。
- onAirのvideo視聴中に、2分経過でbackendのapp-dataに対して視聴履歴を書き込み
- 合計20分経過した時点で、上部のTrail Mapのボタンが光って通知
- ボタンをクリックしてモーダルを開くと、スタンプが押されるeffectとともにスタンプ付与
ポイントを貯めるところはまだ未実装です。
あと、それぞれPRをきっていて一式揃っている環境がないため、reviewappsで動作確認することが現状できません。
lambdaをSAMでlocalで動かしたり、動作確認のための準備がかなり必要なので、動きが見たい場合は声をかけていただいたらdiscordで共有させていただきます。
> Feat: Stamp Collecting

- src/components/Track/Track.tsx
スタンプラリーが動かない問題の対処と、変なAPIコールをしているのでその抑止を入れました
> fix: Suppress invalid API requests

- src/components/Track/Track.tsx
offlineユーザでも、talkが変わったときに表示が切り替わるようにしました
> Fix: Update talk when countdown started even on offline view

- src/components/common/VideoToggleButton.tsx
> fix mongon to nihongo

- src/components/Menu/hooks.ts
https://www.notion.so/cloudnativedays/CICD-a5705beba0e14a1fa13eec27867de795
> CICD2023用のリンクに変更

- src/components/IvsPlayer/IvsPlayer.tsx
- src/components/IvsPlayer/__tests__/IvsPlayer.spec.tsx
- src/components/IvsPlayer/__tests__/__snapshots__/IvsPlayer.spec.tsx.snap
- src/components/Track/Track.tsx
カウントダウンを消しました。伴ってTrack側のstate変数名が適切ではなくなったので修正しました。
> Fix: disable countdown

- src/components/Chat/Chat.tsx
- src/components/Track/Track.tsx
- src/store/auth.ts
This reverts commit 6f592cbbd92a5f5f7a2451a665f6f99231b74d93.
> Revert "fix: Use apiBaseUrl to access action-cable endpoint instead of the same origin host"

- sentry.client.config.js
- sentry.edge.config.js
- sentry.server.config.js
https://docs.sentry.io/platforms/javascript/configuration/sampling/
> disable sending error

- src/components/IvsPlayer/IvsPlayer.tsx
- src/components/IvsPlayer/IvsPlayerVideo.tsx
- src/components/IvsPlayer/__tests__/IvsPlayer.spec.tsx
- src/components/IvsPlayer/__tests__/__snapshots__/IvsPlayer.spec.tsx.snap
- src/components/IvsPlayer/styled.ts
- src/components/Track/Track.tsx
- src/store/__tests__/settings.spec.tsx
- src/store/settings.ts
アーカイブ中のセッションについて、アーカイブ中です、しばらくお待ち下さいという画面を出すようにしました。
加えて、考えうる他のケースでも適切な画面を出すようにしています（liveなのにplayBackUrlが未設定の場合は「配信準備中です」、など）
> feat: Preparing / Archiving component

- src/components/Menu/DesktopMenu.tsx
- src/components/Menu/MobileMenu.tsx
> feat: Remove whiteboard link from header

- .github/renovate.json5
dk-uiの方も、renovate PRのreviewer自動設定を有効化してみました。
> chore: Auto assign reviewers of renovate's PR

- src/store/__tests__/settings.spec.tsx
事前登録したセッションが始まったときに通知するロジックについて、すこし仕様が複雑だったので、テストを書きました。
実装の変更はないので、CICD2023以降で落ち着いたタイミングでレビューいただければ大丈夫です。
> test: Add test cases updateNextRegisteredTalk action

- Dockerfile
ref https://mzqvis6akmakplpmcjx3.hatenablog.com/entry/2020/11/10/231047
> use tini for PID problem

- sentry.client.config.js
- sentry.edge.config.js
- sentry.server.config.js
Sentryの作り直しに伴い、DSNが変わったので差し替えました
> Update sentry dsn

- src/components/Menu/DesktopMenu.tsx
- src/components/Menu/MobileMenu.tsx
- src/components/Menu/hooks.ts
今回参加者ガイドはNotionで提供するようなので、URLを更新します
https://cloudnativedays.slack.com/archives/C04DY0412QG/p1689523448595989?thread_ts=1688309987.577739&cid=C04DY0412QG
> update attendee guide

- sentry.client.config.js
- sentry.edge.config.js
- sentry.server.config.js
> Change sentry dsn

- sentry.client.config.js
- sentry.edge.config.js
- sentry.server.config.js
PostgreSQLの分離でDSNが変わったので再設定しました
> Change DSN

- src/components/Menu/DesktopMenu.tsx
- src/components/Menu/MobileMenu.tsx
https://github.com/cloudnativedaysjp/dreamkast/issues/2173
> 問い合わせフォームへの導線を追加

- src/components/Layout/Layout.tsx
- src/components/Menu/DesktopMenu.tsx
- src/components/Menu/MobileMenu.tsx
- src/components/Menu/styled.ts
- src/pages/[eventAbbr]/ui/info/index.tsx
- Dk側の参加者ダッシュボードへの導線を追加
- 順序など軽微な変更
- /ui/infoに直接アクセスした際に表示できない問題の修正
> メニューまわりの改善

- src/components/Menu/DesktopMenu.tsx
- src/components/Menu/MobileMenu.tsx
Youtube LIVEへのlinkを追加しました。
場所が悩ましいのですが、左側に持ってきた方が良いかと思い、dashboardの左に配置しています。
> feat: Add link to Youtube LIVE

- src/store/settings.ts
keynote中に、すでに完了しているtalkも「開始までしばらくお待ちください」という文言が出てしまう問題に対処しました。
> fix: Correct message on video overlay during keynote

- sentry.client.config.js
- sentry.edge.config.js
- sentry.server.config.js
Sentry VMのメンテナンスに伴って、DSNが変更になったためその反映です
> Updated sentry dsn

- src/pages/[eventAbbr]/ui/admin/check_in_event/index.tsx
- src/pages/[eventAbbr]/ui/admin/check_in_session/index.tsx
> fix: prettier

- src/pages/[eventAbbr]/ui/admin/check_in_event/index.tsx
- src/pages/[eventAbbr]/ui/admin/check_in_session/index.tsx
手元で再現できていないのですが、とりあえずgetServerSidePropsをcheck_in系のページにも入れてみました。
直るか様子を見させてください。
> fix: Implement getServerSideProps for check_in pages

- src/components/Menu/DesktopMenu.tsx
- src/components/Menu/MobileMenu.tsx
- src/components/Menu/hooks.ts
> feat: Update nav link to the one for CNDS2024

- src/pages/[eventAbbr]/ui/index.tsx
> fix: Autoplay community LT

- .github/workflows/cron-remove-label.yml
Ref: https://github.com/cloudnativedaysjp/dreamkast-weaver/pull/94
> fix: SyntaxError

- src/pages/[eventAbbr]/ui/admin/check_in_event/index.tsx
- src/pages/[eventAbbr]/ui/admin/check_in_session/index.tsx
> fix: reload when re-select printer or talk

- src/pages/[eventAbbr]/ui/index.tsx
Reverts cloudnativedaysjp/dreamkast-ui#535
> Revert "chore: disable LT timetable"

- sentry.client.config.js
- sentry.edge.config.js
- sentry.properties
- sentry.server.config.js
> fix sentry dsn

- .github/workflows/build-tag.yml
:bow: :bow: :bow:
https://github.com/cloudnativedaysjp/dreamkast-ui/actions/runs/14701551671/job/41252065938
> bug fix regarding reusable-workflows
